# Generated by Django 3.0.5 on 2020-04-23 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.IntegerField()),
                ('EndTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VideoPath', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('UserID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SplitSpeech',
            fields=[
                ('SplitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Split')),
                ('SpeechPath', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SplitSummary',
            fields=[
                ('SplitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Split')),
                ('SummaryPath', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SplitTranscript',
            fields=[
                ('SplitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Split')),
                ('TranscriptPath', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSplit',
            fields=[
                ('VideoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Video')),
                ('SplitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize.Split')),
            ],
        ),
        migrations.CreateModel(
            name='SplitTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=50)),
                ('SplitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarize.Split')),
            ],
            options={
                'unique_together': {('SplitID', 'Tag')},
            },
        ),
    ]
