# Generated by Django 3.0.5 on 2020-04-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitSpeech',
            fields=[
                ('SplitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Split')),
                ('SpeechPath', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='splitsummary',
            name='SummaryPath',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='splittranscript',
            name='TranscriptPath',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='video',
            name='VideoPath',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='VideoSpeech',
        ),
    ]
