# Generated by Django 3.0.5 on 2020-04-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0002_auto_20200413_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=25),
        ),
    ]
