# Generated by Django 3.0.5 on 2020-04-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0002_auto_20200426_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='SplitPath',
            field=models.CharField(max_length=400),
        ),
    ]
