# Generated by Django 3.0.5 on 2020-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0004_auto_20200426_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='SplitPath',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='splitspeech',
            name='SpeechPath',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='splitsummary',
            name='Summary',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='splittranscript',
            name='TranscriptPath',
            field=models.CharField(max_length=400),
        ),
    ]
