# Generated by Django 3.0.5 on 2020-04-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0002_auto_20200423_1322'),
        ('summarize', '0005_auto_20200426_1218'),
    ]

    operations = [
    ]
