# Generated by Django 3.0.5 on 2020-04-26 19:34

from django.db import migrations, models
import summarize.models


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0006_merge_20200426_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Name',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='VideoPath',
            field=models.FileField(null=True, upload_to=summarize.models.user_directory_path, validators=[summarize.models.file_size], verbose_name=''),
        ),
    ]
