# Generated by Django 3.0.5 on 2020-04-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0007_auto_20200427_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitspeech',
            name='SplitID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Split'),
        ),
        migrations.AlterField(
            model_name='splitsummary',
            name='SplitID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Split'),
        ),
        migrations.AlterField(
            model_name='splittranscript',
            name='SplitID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='summarize.Split'),
        ),
    ]
